######################################################################
# Automatically generated by qmake (3.0) ?? 3? 16 23:20:34 2016
######################################################################

TEMPLATE = app
TARGET = gotocell
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h ui_gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
