######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 9 21:51:15 2016
######################################################################

QT +=core gui
greaterThan(QT_MAJOR_VERSION,4): QT+=widgets
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Age.cpp
