######################################################################
# Automatically generated by qmake (3.0) ?? 3? 16 22:41:24 2016
######################################################################

TEMPLATE = app
TARGET = Age1
INCLUDEPATH += .

# Input
SOURCES += Age.cpp
