######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 18 16:43:40 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LoginDialog.h
FORMS += LoginDialog.ui
SOURCES += Login.cpp LoginDialog.cpp
