######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 18 10:24:03 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h
SOURCES += Calculator.cpp CalculatorDialog.cpp
