######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 18 11:43:19 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += TimeDialog.h
SOURCES += Time.cpp TimeDialog.cpp
