######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 13 14:07:58 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += logindlg.h
SOURCES += logindlg.cpp main.cpp
