######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 16 17:06:30 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ChangeValue.cpp
