######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 16 15:18:09 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Signal.cpp
