######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 10 23:18:23 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += 03.cpp
