######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 18 15:10:48 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h
FORMS += CalculatorDialog.ui
SOURCES += Calculator.cpp CalculatorDialog.cpp
