######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 9 21:50:14 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
