######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 11 12:32:12 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
