######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 16 16:36:27 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += MainWindow.cpp
