######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 16 11:20:45 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Hello.cpp
