######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 16 14:40:06 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Hello.cpp
