######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 16 14:54:20 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Button.cpp
