######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 10 22:38:43 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Button.cpp
